// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckzfxwvpfklzdwksmnkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNremZ4d3ZwZmtsemR3a3NtbmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzY5OTEsImV4cCI6MjA3MzUxMjk5MX0.5cPA4MJ-uVvU3EZgYoAw2kwtXkfF6-9RG2ZLBQMDcAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});